modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://github.com/IAFEnvoy/Tieable/issues"
license = "All Right Reserved"

[[mods]]
modId = "tieable"
version = "${version}"
displayName = "Tieable"
authors = "IAFEnvoy"
description = '''
Add universal tied blocks for decoration.
'''
logoFile = "logo.png"

[[dependencies.tieable]]
modId = "neoforge"
mandatory = true
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tieable]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21,1.21.2)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tieable]]
modId = "architectury"
mandatory = true
versionRange = "[0,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "tieable.mixins.json"